# Generated by Django 2.1.7 on 2019-03-06 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KpopGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=150)),
                ('year_established', models.PositiveIntegerField()),
                ('origin', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('alias', models.CharField(max_length=10)),
                ('group_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpop.GroupCat')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('bday', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('birthplace', models.CharField(max_length=50)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpop.KpopGroups')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('released_date', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpop.KpopGroups')),
            ],
        ),
    ]
